---
#
# Playbook to install Browbeat (Rally + Shaker + PerfKitBenchmarker)
#

- hosts: tester
  vars_files:
    - vars/{{((test|default('')).ansbile|default('')).vars|default('install.yml')}}
  roles:
    - common
    - browbeat
    - { role: browbeat-results, when: browbeat_results_in_httpd}
    - firewall
    - perfkitbenchmarker
    - rally
    - shaker
    - { role: flavors, when: browbeat_create_flavors}
    - { role: images, when: browbeat_upload_guest_images}
    - { role: workloads, when: install_browbeat_workloads}
    - shaker-image
  environment: "{{proxy_env}}"


