---
- name: prepare environment for browbeat installation
  hosts: localhost
  gather_facts: yes
  tags: always
  tasks:
    - name: add tester group hosts to browbeat group
      add_host:
          hostname: "{{ item }}"
          groups:
            - tester
            - browbeat
      with_items: "{{ groups.tester }}"

- name: generate inventory file
  hosts: localhost
  gather_facts: no
  tags: always
  roles:
      - role: inventory-update
        inventory_file_name: 'hosts-prov'

- name: prepare environment for browbeat installation
  hosts: localhost
  gather_facts: yes
  tags: always
  vars:
      hypervisor: "{{ provision.host }}"
      hypervisor_name: hypervisor
  tasks:
    - name: set browbeat_dir
      set_fact:
        browbeat_dir: "{{ ansible_user_dir }}/browbeat"
    - name: Clone browbeat
      vars:
        url: "https://opendev.org/x/browbeat"
        branch: master
      git:
        repo: "{{ url }}"
        version: "{{ branch }}"
        dest: "{{ browbeat_dir }}"
        clone: no
        update: no
    - name: set browbeat_playbook path
      set_fact:
        browbeat_playbook: "{{ browbeat_dir }}/ansible/install/browbeat.yml"
    - name: run ansible
      command: "ansible-playbook -i {{ inventory_file }} {{ browbeat_playbook }}"
